"""1 migration

Revision ID: 0abe3e743913
Revises: adf199a1300f
Create Date: 2023-07-06 22:11:20.064137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abe3e743913'
down_revision = 'adf199a1300f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
