"""2 migration

Revision ID: 982a125eceda
Revises: 0abe3e743913
Create Date: 2023-07-07 00:58:06.985069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982a125eceda'
down_revision = '0abe3e743913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
